name: Build Speedhack Dylib
  
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile Dylib with Clang
        run: |
          clang -dynamiclib \
            -isysroot $(xcrun --sdk iphoneos --show-sdk-path) \
            -arch arm64 \
            -Wno-deprecated-declarations \
            Speedhack.m \
            -framework Foundation \
            -framework CoreFoundation \
            -framework UIKit \
            -framework CoreGraphics \
            -o Speedhack.dylib

      - name: Upload Dylib Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Speedhack-arm64
          path: Speedhack.dylib
